### ISSUE TITLE
There is no output (anti-flood) control - implement queues with configurable antiflood

### ISSUE THREAD

**Issue by Amunak** [WildPHP/Wild-IRC-Bot#23] opened 2015-02-05 23:55 UTC
This is pretty important before we can go live with the rewrite, since an error or something may get the bot easily kicked for flood and potentially k-lined from the server.

- [ ] Implement basic output queue that limits the output at a certain rate
- [ ] Create multiple queues with different priority - some 'slower' and some with higher priority (you *will* want kicks and bans go through before random messages). First the messages from the highest priority queue get processed, then high priority, etc.
- [ ] Make the output rates configurable (with a safe defaults)

**Comment by Yoshi2889** [comment] 2015-02-16 19:59
We probably want timers to be implemented for this.

**Comment by Amunak** [comment] 2015-02-16 20:00
Yeah some kind of timing will have to be involved. I was thinking of somewhat "hard coding" it but if we make timers I guess we can just use those.

**Comment by Yoshi2889** [comment] 2015-08-09 00:57
Should we implement the new queue manager around the say method in Bot.php?

**Comment by Yoshi2889** [comment] 2015-09-04 07:46
We can implement queues on all outgoing data, and have a timer for the flush. How about, say, 3 seconds?

**Comment by Yoshi2889** [comment] 2015-10-05 12:57
This can be implemented in the module that is going to handle connections, possibly? Another possibility would be to create a generic flood control module based on callbacks etc.

**Comment by Yoshi2889** [comment] 2016-10-22 13:00
Duplicate of #65, closing.

**Closed by Yoshi2889** 2016-10-22 13:00 UTC
Labels: bug, enhancement, feature-request
