### ISSUE TITLE
Bot crash when certain user join or quits

### ISSUE THREAD

**Issue by snyte** [WildPHP/Wild-IRC-Bot#58] opened 2015-12-06 16:01 UTC
Bot always crash when this user appear(quit and join)
- lupine (~lupine@[ooo]lupine.users.quakenet.org) Quit (Read error: Connection reset by peer)

**Comment by Yoshi2889** [comment] 2015-12-06 16:03
Hi snyte, thanks for your report!

Are you using the master branch or the architecture-rework branch?

**Comment by snyte** [comment] 2015-12-06 16:11
Master

**Comment by Yoshi2889** [comment] 2015-12-07 21:44
I am unable to reproduce this in architecture-rework. It is probably a module causing the crash.

**Comment by snyte** [comment] 2015-12-10 15:00
Well i said master branch

Fatal error: Uncaught exception 'ErrorException' with message 'Undefined index: message in G:\xampp\ircbot\lib\WildPHP\Connection\IrcConnection.php on line 148' in G:\xampp\ircbot\wildphp.php:52
Stack trace:
#0 G:\xampp\ircbot\lib\WildPHP\Connection\IrcConnection.php(148): {closure}(8, 'Undefined index...', 'G:\\xampp\\ircbot...', 148, Array)
#1 [internal function]: WildPHP\Connection\IrcConnection->processData(':lupine!~lupine...', Object(React\Stream\Stream))
#2 G:\xampp\ircbot\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(64): call_user_func_array(Array, Array)
#3 G:\xampp\ircbot\vendor\react\stream\src\Stream.php(123): Evenement\EventEmitter->emit('data', Array)
#4 [internal function]: React\Stream\Stream->handleData(Resource id #89, Object(React\EventLoop\StreamSelectLoop))
#5 G:\xampp\ircbot\vendor\react\event-loop\StreamSelectLoop.php(227): call_user_func(Array, Resource id #89, Object(React\EventLoop\StreamSelectLoop))
#6 G:\xampp\ircbot\vendor\react\event-loop\StreamSelectLoop.php(201): React\Eve in G:\xampp\ircbot\wildphp.php on line 52

**Comment by Yoshi2889** [comment] 2015-12-10 16:26
Hmm that would require further testing, might be a bug in the parser component. I'll look into it, thanks again for reporting :)

**Comment by snyte** [comment] 2015-12-13 12:15
It's not only lupine, just noticed more of them

* KillaH (KillaH@staff.quakenet.org)
* MadaliN (~MadaliN@Madalin.users.quakenet.org)

**Comment by snyte** [comment] 2015-12-13 14:50
Created a workaround that seems to fix it
In vendor\react\stream\src\Stream.php

public function handleData($stream)
added lines
$data=strtolower($data);
$data=str_replace("[ooo]","",$data);

**Comment by Yoshi2889** [comment] 2016-02-29 09:48
I've been able to confirm this recently by having FatalException live.

It seems the IRC parser we use from the Phergie project is too strict about the IRC RFC, which is often ignored in real-world examples.

I'll have a chat with them about this, but seeing as they specifically made the parser to comply to the RFC, they most likely won't change this. In that case I'll look at creating an alternative or forking it and making it less compliant.

Another solution would be using grawity's parser which doesn't have association and other fanciness: https://github.com/grawity/hacks/tree/master/irc/parsers/php
But it seems better aimed at real-world conventions.

**Comment by Yoshi2889** [comment] 2016-05-22 10:10
This should be fixed in 3.0 once #66 is done.

**Comment by Yoshi2889** [comment] 2017-05-19 22:12
No longer an issue.

**Closed by Yoshi2889** 2017-05-19 22:12 UTC
Labels: bug, help wanted, priority
